// <auto-generated />
using Lab4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab4.Migrations
{
    [DbContext(typeof(EquationContext))]
    [Migration("20231207133633_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("Lab4.SolutionsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("A")
                        .HasColumnType("INTEGER");

                    b.Property<int>("B")
                        .HasColumnType("INTEGER");

                    b.Property<int>("C")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfRoots")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Root1")
                        .HasColumnType("REAL");

                    b.Property<double>("Root2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SolutionsData");
                });
#pragma warning restore 612, 618
        }
    }
}
